# delimiters
delimiters:
  tasks:
    subtasks: ' :: '

# environment definitions
env:
  default: 'development'
  port: 8080

# file encodings
fileEncoding: 'utf-8'

# predefined json options
options:
  flatten:
    'delimiter': '.'

# relative path definitions
paths:
  assets: assets
  data: data
  fonts: fonts
  helpers: helpers
  images: img
  layouts: layouts
  pages: pages
  partials: partials
  javascript: js

# regex
regex:
  stringSeparator: ',; '

# logger
logger:
  logLevel: debug

# panini
panini:
  defaultPageLayout: default